# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이제은
title: Software Enginner
email: dlwpdms1@gmail.com
website: https://github.com/jejeeun

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  일의 시작은 항상 흐름을 이해하는 것부터라고 생각하는, 4년 차 웹 개발자입니다.

  <mark>Java</mark>와 <mark>Spring Framework</mark>를 주력으로 사용하며, 증권 OpenAPI 프로젝트의 초기멤버로 수주까지 경험했습니다.

  백엔드를 중심으로하되, 프론트와 인프라까지 자연스럽게 넘나들며 서비스에 필요한 모든 부분을 함께 다뤄왔습니다.

  ‘왜 이렇게 동작해야 하는가’를 끊임없이 질문하며, 팀에 더 나은 방향을 제안하고 함께 성장하는 과정을 즐깁니다.


content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Asset Chain
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: 2024.01 - 현재
        quote: >
          여러 고객사 환경에 대응하는 OpenAPI 시스템 구축을 통해 대형 증권사 수주 및 적용 성과를 달성했습니다. 기존 증권사 전용 프로그램의 이진 데이터 통신을 HTTP/JSON REST API로 전환하여 외부 연동 가능한 시스템을 개발했으며, 기획부터 구축, 운영, 모니터링까지 전 과정에 직접 참여했습니다.
        description: |
          **증권 OpenAPI 시스템 (2024.04 – 2025.07)**
          - Spring Boot 멀티모듈 기반 공통 캐시 라이브러리 설계 (Redis/Hazelcast 간 YAML 설정만으로 전환)
            - 일부 증권사 외부 캐시 도입 제약으로 유연한 캐시 추상화 구조 필요
          - Spring WebFlux 게이트웨이에 분산 캐시 시스템 연동으로 100만건 메시지 무손실 처리 및 TPS 5,000 안정성 확보
          - Hazelcast Pub/Sub 기반 분산 로깅 시스템 구축 (기존 파일 I/O 제거로 WAS 성능 최적화)
          - Vue3 기반 통합 API 테스트베드 개발 (기존 증권사 테스트베드 오작동 및 WebSocket 인터랙티브 기능 한계 해결)
          - 관리자 백오피스 풀스택 개발 (TR 명세서 엑셀 업로드 자동화 등 운영 편의성 개선)
          - 웹 보안 필터 모듈 개발 및 적용으로 OWASP ZAP 보안감사 통과 (High Risk 취약점 0건)
          - OpenTelemetry 도입하여 분산 트레이싱 기반 실시간 모니터링 시스템 구축으로 원클릭 장애 진단 구현
          - Jenkins 기반 무중단 배포 자동화 파이프라인 구성

          **한화 증권 모니터링 시스템 (2024.01 - 2024.06)**
          - Prometheus + Grafana 기반 실시간 모니터링 시스템 구축
          - 증권사 백엔드 서비스(거래/정산/중계 등) 6개 연동 시스템 통합 모니터링
          - Pushgateway로 배치 작업 메트릭 수집 (기존 실시간 모니터링 불가 해결)
          - 임계값 기반 알람 시스템 구축

      - layout: left
        title: Ejsoft
        sub_title: Software Engineer
        caption: 2021.06 - 2023.12
        quote: >
          환경부 협업 자동차 운행 제한 서비스의 핵심 아키텍처를 재설계하여 시스템 안정성을 확보하고, AI 기반 자동화로 인력 비용 절감 효과를 달성했습니다.
        description: |
          **자동차 운행 제한 시스템**
          - Egovframework 기반 자동차 배출가스 등급별 운행제한 단속·관리 솔루션 개발 (국내 점유율 1위)
          - MariaDB 10억 건 배치 처리 성능 최적화: 10시간 → 3분 단축 (200배 개선)
            - 부하 집중 테이블의 인덱스 전면 재설계 및 CASE WHEN, SYSDATE() 함수 쿼리 최적화
            - 트랜잭션 분할 및 락 타임아웃 최적화로 배치-웹 간 동시성 제어
          - Python YOLOv5 기반 CCTV 번호판 자동 검수 시스템 개발
            - 일 5,000건 3분 처리, 99% 정확도로 주무관 업무 자동화
          - JSP, jQuery, MyBatis, AJAX 기반 행정용 웹 시스템 구축

          **실시간 차량 이미지 검출 솔루션**
          - 딥러닝을 활용한 실시간 차량 이미지 검출, 처리, 저장 솔루션 개발
          - 이미지 처리 파이프라인 구축 및 성능 최적화
          - 실시간 데이터 처리를 위한 시스템 아키텍처 설계

  - title: Other Experience
    layout: list
    content:
      - layout: left
        title: 코아페 (Itez)
        sub_title: Backend Engineer
        caption: 2025.01 - 2025.05
        description: |
          **코아페 - 아파트 단지 주민 대상 지역 멤버십 플랫폼**
          - 기존 Firebase/Firestore 기반 서버리스 아키텍처의 높은 운영비용과 확장성 한계 해결
          - Firebase Cloud Functions를 Spring Boot REST API로 전환하여 월 호출 비용 완전 제거
          - NoSQL 쿼리 제약 해결을 위해 Firestore를 RDS(PostgreSQL)으로 무중단 마이그레이션
          - PostgreSQL JSONB + GIN 인덱스 도입으로 텍스트 검색 3배 성능 향상
          - 사용자 3개월 활성도 분석 기반 차등 포인트 지급 배치 로직 구현
          - Firebase Realtime Database → WebSocket 기반 실시간 통신으로 전환

  - title: Skills
    layout: text
    content: |
      <table class="skills-table">
        <tr>
          <td>Backend</td>
          <td>Java 21, Spring Framework 6.x, Spring Boot 3.2, Swagger, MariaDB 11, MySQL 8.0, PostgreSQL 15, Redis 7.x, Hazelcast 5.x</td>
        </tr>
        <tr>
          <td>Frontend</td>
          <td>Vue.js, JavaScript (ES6+), JSP 2.1, jQuery 3.7</td>
        </tr>
        <tr>
          <td>DevOps</td>
          <td>Docker, Jenkins, Nexus, Nginx, OpenTelemetry, Grafana, Prometheus, Elasticsearch, Logstash, Zipkin</td>
        </tr>
      </table>

  - title: Certificates
    layout: text
    content: |
      <table class="cert-table">
        <thead>
          <tr>
            <th>이름</th>
            <th>등록번호</th>
            <th>발행처</th>
            <th>취득일</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>정보처리기사</td>
            <td>24202020742J</td>
            <td>한국산업인력공단</td>
            <td>2024.09.10</td>
          </tr>
          <tr>
            <td>SQL Developer</td>
            <td>ISQLD-047004046</td>
            <td>한국데이터산업진흥원</td>
            <td>2022.12.02</td>
          </tr>
        </tbody>
      </table>

  - title: Education
    layout: text
    content: |
      <div class="education-line">
        <strong>홍익대학교</strong>
        <span class="degree">컴퓨터공학과 학사 졸업</span>
        <span class="period">(2017.03 ~ 2022.08)</span>
      </div>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
