# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이제은
title: Software Engineer
email: dlwpdms1@gmail.com
website: https://jejeeun.github.io/blog
blog: https://jejeeun.github.io/blog/

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  jejeeun
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  일의 시작은 항상 흐름과 큰 그림을 이해하는 것부터라고 생각하는, 4년차 백엔드 개발자 이제은입니다. <br><br>
  금융·공공 도메인에서 <mark>Java</mark>와 <mark>Spring</mark> 기반 서비스를 개발하면서도 마찬가지로, 단순히 주어진 기능만 구현하는 것이 아니라 "왜 이런 문제가 반복되는가?"를 항상 고민해왔습니다. 증권 OpenAPI 프로젝트에서 각 모듈마다 제각각인 캐시 설정으로 인한 개발 비효율성을 발견했을 때도, 당장의 해결보다는 Redis와 로컬 캐시를 통합 관리하는 공통 라이브러리를 설계해 팀 전체의 근본적인 문제를 해결했습니다.<br><br>
  4년간 개발하며 배운 것이 있습니다. 좋은 개발자는 요구사항을 구현하는 데 그치지 않고, 문제의 본질을 이해해 더 나은 방향을 제시하는 사람임을 배웠습니다. 그 과정에서 긍정적인 태도가 팀 에너지를 높이고 협업을 원활하게 만든다는 사실도 몸소 느꼈습니다. 저는 이러한 낙관을 바탕으로 복잡한 문제를 끝까지 파헤치고 실행 가능한 해결책을 도출하는 데 자신이 있습니다.
content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Asset Chain
        link: https://www.neoframe.com/
        link_text: neoframe.com
        sub_title: Software Engineer
        caption: 2024.01 - 현재
        quote: >
          증권사 대상 금융 IT 솔루션 전문기업. 웹인프라팀 신설과 함께 초기 멤버로 합류하여 회사 첫 OpenAPI 사업 수주에 기여
        description: |
          **증권 OpenAPI 시스템 (2024.04 – 2025.06)**

          Spring Boot 멀티모듈 기반 OpenAPI 플랫폼의 캐시 추상화, 게이트웨이 성능 최적화, 분산 로깅, 모니터링, CI/CD, 보안 강화, 그리고 Vue3 프런트엔드까지 전 영역을 담당했습니다. <br><br>

            - **캐시 추상화** ― 멀티모듈 환경에서 캐시 정책을 통합하고 백엔드 전환을 유연하게 구성
              - Proxy 패턴 기반의 공통 캐시 라이브러리를 설계하고, TTL, 직렬화, 예외 처리를 일관되게 구성
              - DataFetcher와 Template Method를 적용하여 캐시 미스 시 자동 조회와 공통 로직을 처리
              - YAML 한 줄로 Redis ↔ Hazelcast 전환 가능, 캐시 설정 코드 중복 **100% 제거**

            - **성능 최적화** ― 게이트웨이의 대규모 요청 처리 성능을 확보하고 병목 구간을 개선
              - WebFlux 기반 게이트웨이를 비동기 캐시와 연동하여 처리 경로를 비동기화
              - JMeter **5대** 환경에서 **1,000 사용자 × 200 루프** 부하 테스트로 성능을 검증
              - 단일 노드 기준 **TPS 5,000 이상** 달성, 요청 지연 및 **오류율 0%** 유지

            - **분산 로깅** ― 실시간 로그 수집 구조를 설계하여 I/O 병목을 제거하고 대응 속도 개선
              - Hazelcast Ringbuffer 기반의 비동기 로그 처리 파이프라인을 구성
              - 로그 파일 직접 접근 없이도 실시간 로그 수집 및 스트리밍 처리를 구현
              - WAS 파일 **I/O 병목 제거**, 장애 대응 시간 **70% 단축**

            - **모니터링** ― 요청 흐름을 추적하고 호출 관계를 가시화하는 분산 추적 시스템을 도입
              - OpenTelemetry Java Agent를 적용하여 trace ID 기반 요청 단위 추적을 구성
              - Prometheus + Grafana로 지표 수집, AlertManager로 알람 체계를 연동
              - 전체 호출 흐름 시각화 및 병목 지점 분석 시간 대폭 단축

            - **인프라** ― 폐쇄망 환경 대응 배포 구조 및 보안 체계를 구축하여 안정성과 신뢰성 확보
              - Jenkins 기반 Blue-Green 배포 파이프라인을 구성하여 서비스 무중단 배포를 실현
              - NGINX WAF(ModSecurity + OWASP CRS) 및 CSP nonce 기반 콘텐츠 보안 정책을 적용
              - OWASP ZAP 기준 **High/Medium 취약점 0건** 달성, 배포 중단 시간 **0초** 유지

            - **프론트엔드** ― Vue 기반의 관리자 화면 및 API 검증 도구를 구현하여 운영 효율 향상
              - Vue3 기반 관리자 백오피스를 구축, TR 명세서 Excel 업로드 자동화 기능을 구현하여 운영자 업무 효율 개선
              - WebSocket·HTTP 요청을 직접 실행하고 결과를 확인할 수 있는 테스트 화면을 구성하여, API 기능 검증 및 오류 재현을 위한 시각적 인터페이스를 제공
              - 운영자 작업 시간 **90% 단축**, 고객 도입 **오류율 감소**
            
          **한화 증권 모니터링 시스템 (2024.01 - 2024.06)**

          Asset Chain 입사 후 첫 프로젝트로 대형 증권사의 모니터링 시스템 고도화를 담당하였습니다.<br><br>

            - **모니터링 고도화** ― 증권사 핵심 시스템 6개를 대상으로 통합 모니터링 환경을 구축
              - 거래·정산·중계 등 주요 업무 시스템을 연동하여 Prometheus + Grafana 기반 통합 지표 시각화를 구현
              - 배치 작업 모니터링을 위해 Pushgateway를 도입하고, 스케줄 기반 메트릭 수집 체계를 구성
              - 장애 대응 지연을 줄이기 위해 알람 임계값을 정의하고, AlertManager 기반 **자동 알림 시스템**을 구축

          

      - layout: left
        title: Ejsoft
        link: http://ejsoft.co.kr/
        link_text: ejsoft.co.kr
        sub_title: Software Engineer
        caption: 2021.06 - 2023.12
        quote: >
          자동차 배출가스 운행제한 단속 솔루션 전문기업. 전국 9개 지자체 운행제한 시스템 구축 및 운영으로 해당 분야 국내 점유율 1위 보유
        description: |
          **자동차 운행 제한 시스템 (2021.06 ~ 2023.12)**

            - **배치 성능 개선** ― **10억 건** 규모의 대용량 배치 작업 성능을 단계적으로 최적화
              - 복합 인덱스 재설계 및 조건문 단순화, 청크 처리 및 쿼리 리팩토링, 트랜잭션 분리 등을 단계적으로 적용
              - 배치 수행 시간을 **10시간에서 1시간**으로 단축하여 시스템 처리 효율을 대폭 개선
              - 총 **10배 이상**의 배치 처리 속도 향상을 달성, 야간 배치 안정성 및 일간 운영 처리율 향상

            - **행정 시스템 개발** ― 지자체 운행제한 제도 확산에 따른 레거시 시스템 확장
              - 대구 요일제, 부산·광주·세종·울산 계절제 등 신규 운행제한 제도 대응을 위해 레거시 시스템 인터페이스 확장
              - JSP, jQuery, MyBatis, AJAX 기반 행정용 웹 시스템 구축
              - 총 **6개 지자체**에 안정적으로 시스템을 적용하여 사업 확장 및 **매출 증가**에 기여

          **CCTV 번호판 자동 검수 시스템 (2023.01 ~ 2023.12)**

            - **번호판 인식 시스템 개발** ― AI 학습 데이터 구축부터 인식 알고리즘까지 전 과정 설계 및 고도화
              - 전국 **6개 지역**에서 수집한 차량 이미지 **10,867장**을 수작업으로 라벨링하고, 반복 학습과 데이터 정제를 통해 인공지능 모델의 성능을 단계적으로 향상시킴
              - 다양한 번호판 형태(단층/이층, **7~10자리**)를 인식할 수 있도록, 문자 위치·패턴을 조합하는 알고리즘을 직접 설계하고 Python으로 구현
              - 최종 검출·인식 정확도 **99% 달성**, 부산·대구 지역 인식률 각 **0.5%p 향상**, 공개 데이터셋 대비 **2배 규모**의 고품질 데이터셋 확보

  - title: Projects
    layout: list
    content:
      - layout: left
        title: 코아페 (Itez)
        link: https://koape.net/han/html/brandp1.html
        link_text: koape.net
        sub_title: Backend Engineer
        caption: 2025.01 - 2025.05
        description: |
          **코아페 - 아파트 단지 주민 대상 지역 멤버십 플랫폼**

            - **지역 멤버십 플랫폼 고도화** ― Firebase 기반 아키텍처에서 Spring Boot + PostgreSQL로 전환
              - 아파트 단지 주민 대상 플랫폼 '코아페'의 **운영비용 절감**과 **기능 확장성 확보**를 위해 서버리스 아키텍처 개선
              - Firebase Cloud Functions 기반 백엔드를 Spring Boot REST API로 전환하여, **가변 호출 비용을 고정 인프라 비용**으로 최적화
              - 복잡한 검색 및 필터링 기능 요구에 대응하기 위해 NoSQL 구조에서 PostgreSQL로 **점진적 데이터 마이그레이션** 수행
              - **JSONB 컬럼과 GIN 인덱스**를 활용해 텍스트 검색 성능을 향상시키고, 실시간 데이터 처리도 **WebSocket 기반 구조**로 전환

  - title: Skills
    layout: text
    content: |
      **Backend Development**
      - Java 8/17/21, Spring Boot 3.2, Mybatis (3년 이상)  
        - 금융·공공 API 시스템 개발, 멀티모듈 기반 백엔드 구현 경험
      - MySQL 8.0, MariaDB 11, PostgreSQL 15  
        - 도메인별 모델링, 대용량 배치 조회 및 쿼리 성능 개선
      - Redis 7.x, Hazelcast 5.x 
        - OpenAPI 시스템 캐시 및 Pub/Sub 구조 구현, 캐시 백엔드 전환 지원
      - Spring Batch  
        - 정형 파일 파싱 및 Redis/Hazelcast 캐시 적재 배치 구현

      **DevOps & Infrastructure**
      - Docker, Jenkins, GitLab , Nexus
        - RHEL 폐쇄망 서버에서 수동 설치 및 CI/CD 파이프라인 구성, 무중단 배포 운영
      - OpenTelemetry, Prometheus, Grafana, Elasticsearch, Logstash, Zipkin  
        - 증권 API 트랜잭션 추적 및 장애 대응을 위한 모니터링 아키텍처 구축
      - Nginx  
        - API Gateway에 SSL 인증서, WebSocket 프록시, WAF(ModSecurity + OWASP CRS) 구성
        
      **Frontend Development**
      - Vue 3, JavaScript (ES6+) 
        - 관리자 백오피스 및 테스트베드 UI 구현 (WebSocket 기반 실시간 로그 조회 포함)
      - JSP, jQuery  
        - 지자체 공공 시스템 유지보수 및 기능 개선 (전자정부 프레임워크 기반)

  - title: Certificates
    layout: text
    content: |
      <table class="cert-table">
        <thead>
          <tr>
            <th>이름</th>
            <th>등록번호</th>
            <th>발행처</th>
            <th>취득일</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>정보처리기사</td>
            <td>24202020742J</td>
            <td>한국산업인력공단</td>
            <td>2024.09.10</td>
          </tr>
          <tr>
            <td>SQL Developer</td>
            <td>ISQLD-047004046</td>
            <td>한국데이터산업진흥원</td>
            <td>2022.12.02</td>
          </tr>
        </tbody>
      </table>

  - title: Education
    layout: text
    content: |
      <div class="education-line">
        <strong>홍익대학교</strong>
        <span class="degree">컴퓨터공학과 학사 졸업</span>
        <span class="period">(2017.03 ~ 2022.08)</span>
      </div>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
